// src/export/venue-meta.js

export const VENUE_META = new Map([
  ["backed",      { venueType: "dex_spot",  tierLabel: "Issuer" }],
  ["binance",     { venueType: "cex",       tierLabel: "Tier 1" }],
  ["bingx",       { venueType: "cex",       tierLabel: "Tier 2" }],
  ["bitget",      { venueType: "cex",       tierLabel: "Tier 1" }],
  ["bitmart",     { venueType: "cex",       tierLabel: "Tier 2" }],
  ["bybit",       { venueType: "cex",       tierLabel: "Tier 1" }],
  ["coingecko",   { venueType: "hybrid",    tierLabel: "Aggregator" }],
  ["dinari",      { venueType: "dex_spot",  tierLabel: "Issuer" }],
  ["gate",        { venueType: "cex",       tierLabel: "Tier 2" }],
  ["lbank",       { venueType: "cex",       tierLabel: "Tier 2" }],
  ["lighter",     { venueType: "dex_perp",  tierLabel: "DEX" }],
  ["mexc",        { venueType: "cex",       tierLabel: "Tier 2" }],
  ["ondo",        { venueType: "dex_spot",  tierLabel: "Issuer" }],
  ["ourbit",      { venueType: "cex",       tierLabel: "Tier 2" }],
  ["raydium",     { venueType: "dex_spot",  tierLabel: "DEX" }],
  ["remora",      { venueType: "dex_spot",  tierLabel: "DEX" }],
  ["securitize",  { venueType: "dex_spot",  tierLabel: "Issuer" }],
  ["stablestock", { venueType: "dex_spot",  tierLabel: "Issuer" }],
  ["stokr",       { venueType: "dex_spot",  tierLabel: "Issuer" }],
  ["superstate",  { venueType: "dex_spot",  tierLabel: "Issuer" }],
  ["swarm",       { venueType: "dex_spot",  tierLabel: "Issuer" }],
  ["trade.xyz",   { venueType: "dex_spot",  tierLabel: "DEX" }],
  ["vest",        { venueType: "dex_perp",  tierLabel: "DEX" }],
  ["wisdomtree",  { venueType: "dex_spot",  tierLabel: "Issuer" }],
  ["xt",          { venueType: "cex",       tierLabel: "Tier 2" }],
  ["xstocks",     { venueType: "dex_spot",  tierLabel: "DEX" }],
]);
